FROM debian:bullseye

ARG NODE_VERSION=16.16.0

RUN apt-get update
RUN apt-get install -y \
  curl \
  python-is-python3 \
  pkg-config \
  build-essential

RUN curl https://get.volta.sh | bash
ENV VOLTA_HOME /root/.volta
ENV PATH /root/.volta/bin:$PATH
RUN volta install node@${NODE_VERSION}

#######################################################################

RUN mkdir /app
WORKDIR /app

COPY . .
CMD [ "npm", "run", "dev" ]
