name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
      - master
      - beta
      - christmas

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Create debug config
        run: cp ./common/config/debug-config.example.json ./common/config/debug-config.json

      - name: Run server tsc
        run: npm run server:tsc

      - name: Run biome
        run: npm run lint

  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Create debug config
        run: cp ./common/config/debug-config.example.json ./common/config/debug-config.json

      - name: Run tests
        run: npm run test:unit

  snapshot-tests:
    name: Snapshot Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Create debug config
        run: cp ./common/config/debug-config.example.json ./common/config/debug-config.json

      - name: Run tests
        run: npm run test:snapshot

  api-tests:
    name: API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci
          sudo apt-get install -y curl
          sudo apt-get install -y jq

      - name: Create debug config
        run: cp ./common/config/debug-config.example.json ./common/config/debug-config.json

      - name: Build project
        run: npm run build

      - name: Run tests
        run: ./tests/test-api.sh

  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: End to End Tests
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Create debug config
      run: cp ./common/config/debug-config.example.json ./common/config/debug-config.json

    - name: Build the server
      run: npm run build

    - name: Run Playwright tests
      run: npm run test:e2e

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  db:
    name: Databse Tests
    runs-on: ubuntu-latest
    container: node:18.20-bookworm-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: hctcg
          POSTGRES_PASSWORD: hctcg
          POSTGRES_DATABASE: hctcg
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL
        run: npm run test:db
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_USER: hctcg
          POSTGRES_PORT: 5432


  build-docker:
    name: Test Can Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: docker buildx build .
